# ==============================================================================
# Project: GCB — Anthropogenic Effects on the Elementome
#
# Script: 00_Prepare_Construction_Data.R
#
# Purpose:
#   Reconstruct annual global mass series for construction materials used in
#   the elemental-mobilization analysis. The workflow estimates the extraction
#   and use of aggregates, clay, and carbonate rocks associated with concrete,
#   asphalt, bricks, road and building bases, railway ballast, cement, and lime.
#
#   The reconstruction integrates published material-flow estimates,
#   mineral-production statistics, population data, railway statistics, and
#   literature-derived engineering assumptions. Missing periods are reconstructed
#   using interpolation, extrapolation, or source-specific assumptions documented
#   in the Supplementary Methods and within the corresponding workflow sections.
#
# Analytical framework:
#   Annual material-use series are reconstructed separately for:
#     - aggregates;
#     - clay; and
#     - carbonate rocks represented by the reconstructed limestone series.
#
#   Uncertainty in the reconstructed material masses is propagated where
#   applicable using Monte Carlo simulation or source-specific uncertainty
#   estimates. The resulting annual best estimates and SDs are used as inputs
#   by `01_Elemental_Mobilization.R`.
#
# Units:
#   Final construction-material mass series are expressed in Tg yr-1.
#   Intermediate calculations may use tonnes, Tg, km, population-based rates,
#   or other source-specific units; conversions are documented where applied.
#
# Temporal coverage:
#   Annual series are reconstructed over the historical period required by the
#   elemental-mobilization analysis, subject to the temporal coverage of the
#   underlying source datasets.
#
# Author:
#   Fernando Coello Sanz
#
# Affiliation:
#   CREAF
#
# Contact:
#   f.coello@creaf.uab.cat
#
# Repository:
#   https://github.com/fercoello/GCB-Human_Elementome
#
# Created:
#   2026-01-30
#
# Last updated:
#   2026-10-07
#
# R version:
#   R 4.5.1
#
# Main dependencies:
#   tidyverse, readxl, here, zoo, truncnorm
#
# Main input sources:
#   - Construction-material estimates from Plank et al. (2022)
#   - UN Statistics data for bitumen consumption
#   - USGS cement- and lime-production statistics
#   - Our World in Data global population series
#   - Material-recycling estimates from Krausmann et al.
#   - Mining-production data compiled for this study
#   - Historical and World Bank railway-length statistics
#   - Railway-gauge information
#
#   Complete references, source locations, temporal coverage, and assumptions
#   are documented in the Supplementary Methods and in source-specific comments
#   within the script.
#
# Inputs:
#   data/data_construction/data_construction_resrecenv.xlsx
#   data/data_construction/UNdata_Export_20260122_111521360/
#     UNdata_Export_20260122_111521360.csv
#   data/data_construction/USGS_cement.xlsx
#   data/data_construction/population/population.csv
#   data/data_construction/Krausman_recycling.xlsx
#   data/data_FM1_mining_production.xlsx
#   data/data_construction/railways/Railway_length_world.xlsx
#
# Output:
#   data/data_construction.csv
#
# Reproducibility:
#   A fixed random-number seed is used for Monte Carlo calculations. Run the
#   script from the root directory of the RStudio project. File paths are
#   constructed relative to the project root using here::here().
#
# Data availability:
#   The harmonized output dataset generated by this script is intended for
#   redistribution with the repository. Original third-party source files are
#   not necessarily redistributed; where this applies, source references and
#   instructions for obtaining the original data are provided in the
#   Supplementary Methods and source-specific comments.
#
# License:
#   Code: MIT License
#   Data and documentation: CC BY 4.0
#
# Citation:
#   See repository citation information.
# ==============================================================================

# ==============================================================================


# 00. Setup ----------------------------------------------------------------
# Purpose:
#   1. Load the packages required by the workflow.
#   2. Define project paths.
#   3. Declare reproducibility settings.
#   4. Declare important constants and reconstruction assumptions in one place.

# Load packages -------------------------------------------------------------

library(tidyverse)
library(readxl)
library(here)
library(zoo)       # na.approx()
library(truncnorm)


# Define project paths ------------------------------------------------------

DATA_DIR <- here("data")
CONSTRUCTION_DIR <- file.path(DATA_DIR, "data_construction")
RAIL_DIR <- file.path(CONSTRUCTION_DIR, "railways")

# Brick-production assumptions ----------------------------------------------

# Per-capita brick-production rates used to extend the Plank et al. (2022)
# series outside its original 1900–2016 temporal coverage.
BRICK_PC_1900 <- 0.000226
BRICK_PC_2016 <- 0.0004001017

# Coefficients of variation associated with the boundary years of the
# Plank et al. (2022) brick-production series.
BRICK_CV_1900 <- 0.23643870
BRICK_CV_2016 <- 0.09367788

# Aggregate-reconstruction assumptions --------------------------------------
  
# Historical onset of concrete and asphalt production following the
# assumptions adopted by Plank et al. (2022).

CONCRETE_START_YEAR <- 1850
ASPHALT_START_YEAR <- 1870
PLANK_START_YEAR <- 1900
PLANK_END_YEAR <- 2016

# Material composition of concrete and asphalt.
# Plank et al. (2022) assume cement:aggregate and bitumen:aggregate mass
# ratios of 1:5 and 1:19, respectively.
CONCRETE_AGGREGATE_FRACTION <- 5 / 6
ASPHALT_AGGREGATE_FRACTION <- 19 / 20

# Road-base aggregate-to-bitumen ratios from Krausmann et al. (2017).
ROAD_BASE_RATIO_PRE1940 <- 100
ROAD_BASE_RATIO_POST1980 <- 50
ROAD_BASE_TRANSITION_START <- 1940
ROAD_BASE_TRANSITION_END <- 1980
ROAD_BASE_BITUMEN_FRACTION <- 0.05
ROAD_BASE_CV <- 0.30

# Building-subbase aggregate requirements from Krausmann et al. (2017).
BUILDING_BASE_CONCRETE_RATIO <- 0.07
BUILDING_BASE_BRICK_RATIO <- 0.045
BUILDING_BASE_CV <- 0.33

# Boundary values of the virgin aggregate fraction from
# Krausmann et al. (2017).
VIRGIN_AGGREGATE_1900 <- 0.49431566
VIRGIN_AGGREGATE_2010 <- 0.38605950

# Railway-ballast assumptions -----------------------------------------------

# Thresholds used to identify implausible jumps in historical national
# railway-length series.
RAIL_JUMP_KM <- 500
RAIL_JUMP_PROP <- 0.10
RAIL_JUMP_WINDOW <- 10

# Miatto et al. (2017) relationship between railway gauge (m) and ballast
# intensity (t km-1).
BALLAST_GAUGE_SLOPE <- 2119.3
BALLAST_GAUGE_INTERCEPT <- -581.2

# Annual ballast input associated with maintenance and renewal.
# The range accounts jointly for tamping, ballast cleaning, and complete
# renewal operations.
BALLAST_RENEWAL_MIN <- 0.017
BALLAST_RENEWAL_BEST <- 0.035
BALLAST_RENEWAL_MAX <- 0.075

# Monte Carlo settings.
N_SIM_RAIL <- 10000L
MC_COVERAGE_RAIL <- 0.95

set.seed(27)

# Cement-derived clay assumptions -------------------------------------------

# Concrete is assumed to contain 1 part cement and 5 parts aggregates.
CEMENT_FRACTION_CONCRETE <- 1 / 6

# Clay is assumed to represent 20% of cement mass.
CLAY_FRACTION_CEMENT <- 0.20

# First year from which the USGS cement-production series is used directly.
USGS_CEMENT_START_YEAR <- 1927
# Limestone assumptions -----------------------------------------------------

# Limestone demand associated with cement production is assumed to equal
# cement production on a 1:1 mass basis.
LIMESTONE_TO_CEMENT_RATIO <- 1

# Lime production is converted to limestone-equivalent mass assuming
# 1.8 units of limestone per unit of lime produced.
LIMESTONE_TO_LIME_RATIO <- 1.8

# Boundary years used to extend per-capita lime production outside the
# temporal coverage of the mining dataset.
LIME_PC_START_YEAR <- 1930
LIME_PC_END_YEAR <- 2020

# 01. Load source data ------------------------------------------------------

# Loading data ------------------------------------------------------------

## Historical construction-material estimates -------------------------------
# Historical concrete, asphalt, and brick production estimates were obtained
# from Plank et al. (2022). These data provide annual global material-use
# estimates for 1900–2016 and form the basis for reconstructing aggregate and
# clay demand associated with concrete, asphalt, and brick production.
#
# Plank et al. (2022) also report uncertainty ranges, which are used below to
# derive annual coefficients of variation for uncertainty propagation.
#
# Reference:
# Plank et al. (2022), Resources, Conservation and Recycling,
# https://doi.org/10.1016/j.resconrec.2021.106122

data_construction_resrecenv <- read_excel("data/data_construction/data_construction_resrecenv.xlsx") %>% rename(Year = 1)

## Bitumen consumption ------------------------------------------------------

# Global bitumen consumption for non-energy uses was obtained from the United
# Nations Statistics Division. These data are used to extend the asphalt-based
# aggregate reconstruction beyond the temporal coverage of Plank et al. (2022).
#
# Aggregate demand associated with asphalt production is estimated assuming an
# aggregate-to-bitumen mass ratio of 19:1, following Plank et al. (2022).
#
# Source:
# United Nations Statistics Division (2026), bitumen — non-energy uses.
UNdata_bitumen <- read_csv("data/data_construction/UNdata_Export_20260122_111521360/UNdata_Export_20260122_111521360.csv") %>%
  rename(Country = 1, Commodity = 2, Year = 3, Unit = 4, Value = 5)

## Cement production --------------------------------------------------------

# Global cement-production statistics were obtained from the United States
# Geological Survey (USGS). These data are used to extend concrete-related
# aggregate demand beyond the 1900–2016 series of Plank et al. (2022) and to
# estimate clay and limestone demand associated with cement production.
#
# Concrete aggregate demand is estimated using a cement-to-aggregate mass ratio
# of 1:5, following Plank et al. (2022).
#
# Source:
# Hatfield (2026a), USGS cement statistics.
USGS_cement <- read_excel("data/data_construction/USGS_cement.xlsx")

## Global population --------------------------------------------------------

# Historical global population data were obtained from Our World in Data.
# Population is used to extend selected construction-material series outside
# their original temporal coverage when per-capita material-use assumptions are
# applied, particularly for brick and lime production.
#
# Only the global population series is retained.
population_OWD <- read_csv("data/data_construction/population/population.csv") %>% rename(Population = 4) %>%
  filter(Year >1819 & Entity == "World") %>% select(Year, Population)

## Virgin aggregate fraction ------------------------------------------------

# Estimates of the fraction of aggregate demand supplied by newly extracted
# (virgin) material were obtained from Krausmann et al. (2017).
#
# These fractions are applied to road-base and building-subbase aggregate
# demand to avoid double counting recycled or reused construction materials.
# For years outside the original temporal coverage, the earliest available
# fraction (1900) is propagated backward and the latest available fraction
# (2010) is propagated forward.

Krausmann_recycling <- read_excel("data/data_construction/Krausman_recycling.xlsx")

## Mining-production data ---------------------------------------------------

# The harmonized mining dataset compiled for this study is used here only to
# obtain lime-production statistics.
#
# Limestone demand associated with lime production is estimated by converting
# reported lime production to limestone-equivalent mass using the conversion
# factor defined below.
#
# Complete mining-data provenance and reconstruction procedures are documented
# in the Supplementary Methods and the README sheet of data_FM1.xlsx.

data_mining <- read_excel("data/data_FM1_mining_production.xlsx",sheet = "FM1_long_data")

## Railway length and gauge data --------------------------------------------

# Historical national railway-length statistics are used to reconstruct annual
# railway additions and, subsequently, aggregate demand for railway ballast.
#
# Railway-length data prior to 1995 were compiled from historical national
# statistics reported by Mitchell (1975, 1998a, 1998b). More recent railway
# statistics were obtained from the World Bank.
#
# Annual additions are calculated from year-to-year changes in operated railway
# length. Implausible jumps associated with changes in political boundaries,
# country definitions, or inconsistencies between historical sources are
# identified and filtered later in the workflow.

Railway_length_world_prior1995 <- read_excel("data/source_compilations/Railway_length_gauge_world.xlsx", sheet = "Historical_length")
Railway_length_world_post1995 <- read_excel("data/source_compilations/Railway_length_gauge_world.xlsx", sheet = "WB_1995_2021")

# Country-specific railway-gauge information was compiled from Puffert (2009).
# The most common gauge and, where available, minimum and maximum gauges are
# used to estimate ballast intensity using the relationship developed by
# Miatto et al. (2017):
#
#   ballast intensity = 2119.3 * gauge - 581.2
#
# Gauge-related variation is propagated later as uncertainty in railway-ballast
# demand.
Railway_gauges <- read_excel("data/source_compilations/Railway_length_gauge_world.xlsx", sheet = "Gauge")


# 02. Clay: brick production ------------------------------------------------

# Historical global brick production was obtained from Plank et al. (2022):
# https://doi.org/10.1016/j.resconrec.2021.106122
#
# The source provides annual global estimates of brick, concrete, and asphalt
# production for 1900–2016, together with coefficients of variation (CVs) used
# here to represent uncertainty.
#
# Brick production is used to estimate clay demand associated with bricks.
# Outside the temporal coverage of Plank et al. (2022), brick production is
# extrapolated using global population and constant per-capita production rates
# derived from the boundary years of the source series.


## Aggregate material categories --------------------------------------------

# Sum all source columns corresponding to concrete, asphalt, and bricks while
# retaining the annual CV reported by Plank et al. (2022).
#
# Concrete and asphalt totals are retained because they are subsequently used
# in the aggregate reconstruction.

data_aggregate <- data_construction_resrecenv %>%
  mutate(
    Concrete_total = rowSums(
      select(., starts_with("Concrete")),
      na.rm = TRUE
    ),
    Asphalt_total = rowSums(
      select(., starts_with("Asphalt")),
      na.rm = TRUE
    ),
    Brick_total = rowSums(
      select(., starts_with("Brick")),
      na.rm = TRUE
    )
  ) %>%
  select(
    Year,
    Concrete_total,
    Asphalt_total,
    Brick_total,
    CV
  )


## Extend brick-production series -------------------------------------------

# For years before 1900, the per-capita brick-production rate observed at the
# beginning of the Plank et al. (2022) series is applied to global population.
#
# For years after 2016, the corresponding rate at the end of the series is
# applied.
#
# The CVs from the boundary years are similarly propagated backward and
# forward to characterize uncertainty outside the original data coverage.
#
# Brick production is converted from Mt to Gt. Brick mass is assumed to
# represent clay demand directly (1:1 mass relationship).

data_brick <- data_aggregate %>%
  select(
    Year,
    Brick_total,
    CV
  ) %>%
  right_join(
    population_OWD,
    by = "Year"
  ) %>%
  mutate(
    brick_per_capita = Brick_total / Population,
    
    Brick_total = case_when(
      Year < 1900 ~ BRICK_PC_1900 * Population,
      Year > 2016 ~ BRICK_PC_2016 * Population,
      TRUE ~ Brick_total
    ),
    
    CV = case_when(
      Year < 1900 ~ BRICK_CV_1900,
      Year > 2016 ~ BRICK_CV_2016,
      TRUE ~ CV
    ),
    
    # Convert Mt to Gt
    Brick_total = Brick_total * 1e-3,
    
    # Clay demand associated with brick production
    clay_brick = Brick_total,
    clay_brick_sd = clay_brick * CV
  ) %>%
  arrange(Year)


# 03. Aggregates ------------------------------------------------------------

# Global aggregate extraction is reconstructed from four major uses:
#   1. concrete production;
#   2. asphalt production;
#   3. road-base and building-subbase construction; and
#   4. railway ballast.
#
# Concrete and asphalt estimates are based primarily on Plank et al. (2022),
# while road and building bases follow the material-intensity assumptions of
# Krausmann et al. (2017) and Miatto et al. (2017).
#
# Only virgin aggregate extraction is ultimately retained in order to avoid
# counting recycled or reused construction materials as new lithospheric
# mobilization.


## Concrete and asphalt -----------------------------------------------------

# Plank et al. (2022) provide historical global concrete and asphalt
# production for 1900–2016.
#
# To extend these series backward, concrete production is assumed to begin in
# 1850 and asphalt production in 1870, following the historical assumptions
# adopted by Plank et al. Production is linearly increased from zero in the
# respective starting year to the value reported for 1900.
#
# The 1900 CV is propagated backward to characterize uncertainty before the
# beginning of the original Plank et al. series.


# Helper function: linear increase from zero at `start_year` to the observed
# value in 1900.

ramp_to_1900 <- function(year, start_year, value_1900) {
  
  case_when(
    year < start_year ~ 0,
    year <= PLANK_START_YEAR ~
      (year - start_year) /
      (PLANK_START_YEAR - start_year) *
      value_1900,
    TRUE ~ NA_real_
  )
}


# Create a complete annual series beginning in 1850.

construction_years <- tibble(
  Year = seq(
    CONCRETE_START_YEAR,
    max(data_aggregate$Year, na.rm = TRUE)
  )
)

data_aggregate_expanded <- construction_years %>%
  left_join(
    data_aggregate %>%
      select(
        Year,
        Concrete_total,
        Asphalt_total,
        CV
      ),
    by = "Year"
  )


# Extract the first observed values from the Plank et al. series.

concrete_1900 <- data_aggregate %>%
  filter(Year == PLANK_START_YEAR) %>%
  pull(Concrete_total) %>%
  first()

asphalt_1900 <- data_aggregate %>%
  filter(Year == PLANK_START_YEAR) %>%
  pull(Asphalt_total) %>%
  first()


# Reconstruct concrete and asphalt production before 1900 and convert the
# original production units from Mt to Gt.

data_aggregate_expanded <- data_aggregate_expanded %>%
  mutate(
    Concrete_total = if_else(
      Year < PLANK_START_YEAR,
      ramp_to_1900(
        Year,
        start_year = CONCRETE_START_YEAR,
        value_1900 = concrete_1900
      ),
      Concrete_total
    ),
    
    Asphalt_total = if_else(
      Year < PLANK_START_YEAR,
      ramp_to_1900(
        Year,
        start_year = ASPHALT_START_YEAR,
        value_1900 = asphalt_1900
      ),
      Asphalt_total
    ),
    
    CV = if_else(
      Year < PLANK_START_YEAR,
      BRICK_CV_1900,
      CV
    ),
    
    # Convert Mt to Gt
    Concrete_total = Concrete_total * 1e-3,
    Asphalt_total = Asphalt_total * 1e-3,
    
    Concrete_total_sd = Concrete_total * CV,
    Asphalt_total_sd = Asphalt_total * CV
  )

## Extend concrete and asphalt beyond 2016 ----------------------------------

# For 2017 onward, concrete production is reconstructed from global USGS
# cement-production statistics. A cement-to-aggregate ratio of 1:5 implies
# that total concrete mass is six times the cement mass.
#
# Asphalt production is reconstructed from UN statistics on bitumen used for
# non-energy purposes. A bitumen-to-aggregate ratio of 1:19 implies that total
# asphalt mass is 20 times the bitumen mass.
#
# These relationships follow Plank et al. (2022). Their performance was checked
# against the Plank et al. series during overlapping years before applying them
# beyond 2016.
#
# The CV from the final year of the Plank et al. series is propagated forward
# to characterize uncertainty.


# Asphalt from UN bitumen statistics.

data_bitumen_post2016 <- UNdata_bitumen %>%
  filter(
    Commodity == "Bitumen - Non-energy uses",
    Year > 1990
  ) %>%
  group_by(Year) %>%
  summarise(
    bitumen_production = sum(Value, na.rm = TRUE) * 1e-3,
    .groups = "drop"
  ) %>%
  mutate(
    Asphalt_total =
      bitumen_production / (1 - ASPHALT_AGGREGATE_FRACTION)
  )


# Concrete from USGS cement statistics.

data_cement_post2016 <- USGS_cement %>%
  transmute(
    Year,
    cement = Value,
    Concrete_total =
      cement / (1 - CONCRETE_AGGREGATE_FRACTION)
  ) %>%
  drop_na()


# Combine the reconstructed post-2016 concrete and asphalt series.

data_aggregates_post2016 <- data_cement_post2016 %>%
  filter(Year > PLANK_END_YEAR) %>%
  select(
    Year,
    Concrete_total
  ) %>%
  left_join(
    data_bitumen_post2016 %>%
      filter(Year > PLANK_END_YEAR) %>%
      select(
        Year,
        Asphalt_total
      ),
    by = "Year"
  ) %>%
  mutate(
    CV = BRICK_CV_2016,
    Concrete_total_sd = Concrete_total * CV,
    Asphalt_total_sd = Asphalt_total * CV
  )

## Combine concrete and asphalt series --------------------------------------

data_concrete_asphalt <- bind_rows(
  data_aggregate_expanded %>%
    filter(Year <= PLANK_END_YEAR),
  data_aggregates_post2016
) %>%
  arrange(Year) %>%
  mutate(
    # Aggregate fraction of total concrete and asphalt mass
    aggregates_concrete =
      Concrete_total * CONCRETE_AGGREGATE_FRACTION,
    
    aggregates_asphalt =
      Asphalt_total * ASPHALT_AGGREGATE_FRACTION,
    
    aggregates_concrete_sd =
      Concrete_total_sd * CONCRETE_AGGREGATE_FRACTION,
    
    aggregates_asphalt_sd =
      Asphalt_total_sd * ASPHALT_AGGREGATE_FRACTION
  )

## Road-base aggregates -----------------------------------------------------

# Aggregate demand for asphalt-road base courses is estimated from bitumen
# consumption following Krausmann et al. (2017) and Miatto et al. (2017).
#
# The aggregate-to-bitumen ratio is assumed to be:
#   - 100:1 before 1940;
#   - linearly declining from 100:1 to 50:1 during 1940–1980;
#   - 50:1 from 1980 onward.
#
# Bitumen represents 5% of total asphalt mass in the Plank et al. formulation.
# A relative uncertainty of ±30% (1 SD) is applied following Krausmann et al.
# (2017).


road_base_ratio <- tibble(
  Year = data_concrete_asphalt$Year
) %>%
  mutate(
    aggregate_to_bitumen = case_when(
      Year < ROAD_BASE_TRANSITION_START ~ ROAD_BASE_RATIO_PRE1940,
      
      Year >= ROAD_BASE_TRANSITION_END ~ ROAD_BASE_RATIO_POST1980,
      
      TRUE ~
        ROAD_BASE_RATIO_PRE1940 +
        (Year - ROAD_BASE_TRANSITION_START) *
        (
          ROAD_BASE_RATIO_POST1980 -
            ROAD_BASE_RATIO_PRE1940
        ) /
        (
          ROAD_BASE_TRANSITION_END -
            ROAD_BASE_TRANSITION_START
        )
    )
  )


aggregates_base_roads <- data_concrete_asphalt %>%
  left_join(
    road_base_ratio,
    by = "Year"
  ) %>%
  mutate(
    aggregate_base_road =
      Asphalt_total *
      ROAD_BASE_BITUMEN_FRACTION *
      aggregate_to_bitumen,
    
    aggregate_base_road_sd =
      aggregate_base_road * ROAD_BASE_CV
  ) %>%
  select(
    Year,
    aggregate_base_road,
    aggregate_base_road_sd
  )

## Building-subbase aggregates ---------------------------------------------

# Aggregate demand associated with building subbase layers is estimated from
# concrete and brick production following Krausmann et al. (2017), based on
# Miatto et al. (2017).
#
# Aggregate requirements are assumed to correspond to:
#   - 0.07 units of aggregate per unit of concrete;
#   - 0.045 units of aggregate per unit of bricks.
#
# A relative uncertainty of ±33% (1 SD) is applied to the combined estimate.

aggregates_base_buildings <- data_brick %>%
  select(
    Year,
    Brick_total
  ) %>%
  full_join(
    data_concrete_asphalt %>%
      select(
        Year,
        Concrete_total
      ),
    by = "Year"
  ) %>%
  mutate(
    Brick_total = replace_na(Brick_total, 0),
    Concrete_total = replace_na(Concrete_total, 0),
    
    aggregate_brick =
      Brick_total * BUILDING_BASE_BRICK_RATIO,
    
    aggregate_concrete =
      Concrete_total * BUILDING_BASE_CONCRETE_RATIO,
    
    aggregates_base_buildings =
      aggregate_brick + aggregate_concrete,
    
    aggregates_base_buildings_sd =
      aggregates_base_buildings * BUILDING_BASE_CV
  ) %>%
  select(
    Year,
    aggregates_base_buildings,
    aggregates_base_buildings_sd,
    aggregate_concrete,
    aggregate_brick
  )

## Virgin aggregate extraction ---------------------------------------------

# Road and building-base demand can partly be supplied by recycled or reused
# construction materials. Because the objective is to estimate mobilization
# from the lithosphere, only the fraction supplied by virgin aggregates is
# retained.
#
# Virgin aggregate fractions are taken from Krausmann et al. (2017).
# The earliest available value (1900) is propagated backward, and the latest
# available value (2010) is propagated forward beyond the source coverage.
#
# Uncertainties in road-base and building-subbase demand are treated as
# independent and combined by quadrature.

aggregates_bases <- full_join(
  aggregates_base_buildings,
  aggregates_base_roads,
  by = "Year"
) %>%
  mutate(
    across(
      c(
        aggregates_base_buildings,
        aggregates_base_buildings_sd,
        aggregate_base_road,
        aggregate_base_road_sd
      ),
      ~ replace_na(.x, 0)
    )
  ) %>%
  left_join(
    Krausmann_recycling %>%
      select(
        Year,
        Sand_gravel_Virgin_perc
      ),
    by = "Year"
  ) %>%
  mutate(
    Sand_gravel_Virgin_perc = case_when(
      Year < 1901 ~ VIRGIN_AGGREGATE_1900,
      Year > 2010 ~ VIRGIN_AGGREGATE_2010,
      TRUE ~ Sand_gravel_Virgin_perc
    ),
    
    aggregate_bases_all =
      aggregates_base_buildings +
      aggregate_base_road,
    
    aggregate_bases_sd = sqrt(
      aggregates_base_buildings_sd^2 +
        aggregate_base_road_sd^2
    ),
    
    aggregate_bases_virgin =
      aggregate_bases_all *
      Sand_gravel_Virgin_perc,
    
    aggregate_bases_virgin_sd =
      aggregate_bases_sd *
      Sand_gravel_Virgin_perc
  ) %>%
  arrange(Year)

## Railway ballast ----------------------------------------------------------

# Historical national railway-length series are combined with recent World
# Bank data to reconstruct annual railway additions. Missing intermediate years
# are interpolated, and implausible observations or discontinuities are filtered
# before estimating newly constructed railway length.
#
# Country-specific railway gauges are then used to estimate aggregate demand
# for railway ballast. Ballast associated with both new construction and
# maintenance/renewal is included.
### Functions ---------------------------
sd_from_range <- function(
    min_value,
    max_value,
    coverage = MC_COVERAGE_RAIL
) {
  
  z <- qnorm((1 + coverage) / 2)
  
  (max_value - min_value) /
    (2 * z)
}


rnorm_trunc0 <- function(
    n,
    mean,
    sd
) {
  
  if (is.na(mean) || is.na(sd)) {
    return(rep(NA_real_, n))
  }
  
  if (sd <= 0) {
    return(rep(max(mean, 0), n))
  }
  
  truncnorm::rtruncnorm(
    n,
    a = 0,
    b = Inf,
    mean = mean,
    sd = sd
  )
}
### Combine and interpolate railway-length series ---------------------------

rail_hist_long <- Railway_length_world_prior1995 %>%
  pivot_longer(
    cols = -Year,
    names_to = "Country",
    values_to = "Length_km"
  )

rail_wb_long <- Railway_length_world_post1995 %>%
  pivot_longer(
    cols = matches("^\\d{4}$"),
    names_to = "Year",
    values_to = "Length_km"
  ) %>%
  mutate(
    Year = as.numeric(Year),
    Country = `Country Name`
  ) %>%
  select(
    Country,
    Year,
    Length_km
  ) %>%
  filter(!is.na(Length_km))


# Combine historical and World Bank observations.

rail_full <- bind_rows(
  rail_hist_long,
  rail_wb_long
)

rail_full_clean <- rail_full %>%
  arrange(
    Country,
    Year
  ) %>%
  group_by(
    Country,
    Year
  ) %>%
  summarise(
    # When duplicate country-year observations occur, retain the last value.
    Length_km = last(Length_km),
    .groups = "drop"
  )

### Screen observations and interpolate missing years -----------------------

# Complete annual national time series and linearly interpolate intermediate
# missing years.
#
# Very high reported observations are additionally screened within each
# country. Observations exceeding the 90th percentile plus three SD of reported
# railway length are treated as potential outliers, removed, and interpolated
# from neighbouring years.

rail_full_complete <- rail_full_clean %>%
  group_by(Country) %>%
  complete(
    Year = full_seq(Year, 1)
  ) %>%
  arrange(
    Year,
    .by_group = TRUE
  ) %>%
  mutate(
    Length_km_original = Length_km,
    was_real = !is.na(Length_km_original),
    
    p90_real = quantile(
      Length_km_original[was_real],
      0.90,
      na.rm = TRUE
    ),
    
    sd_real = sd(
      Length_km_original[was_real],
      na.rm = TRUE
    ),
    
    upper_thr = p90_real + 3 * sd_real,
    
    outlier_high =
      was_real &
      Length_km_original > upper_thr,
    
    Length_km_clean = if_else(
      outlier_high,
      NA_real_,
      Length_km_original
    ),
    
    Length_km = na.approx(
      Length_km_clean,
      x = Year,
      na.rm = FALSE
    ),
    
    data_type = case_when(
      was_real & !outlier_high ~ "real",
      outlier_high ~ "outlier_removed_interpolated",
      !was_real ~ "interpolated"
    )
  ) %>%
  ungroup() %>%
  select(
    -p90_real,
    -sd_real,
    -upper_thr
  )
### Estimate annual additions and filter discontinuities --------------------

# Annual additions are calculated as year-to-year changes in railway length.
#
# Large positive jumps may reflect changes in national boundaries, statistical
# coverage, or inconsistencies between historical sources rather than actual
# construction. Jumps larger than 500 km and 10% of the country's maximum
# railway length are therefore flagged.
#
# For flagged years, cumulative negative changes within a ±10-year window are
# examined. If these losses exceed 10% of maximum network length, the positive
# jump is treated as an artefact and assigned zero additional railway length.
#
# Negative annual changes are also set to zero because this reconstruction
# targets newly added railway rather than net changes in network length.

rail_diff <- rail_full_complete %>%
  group_by(Country) %>%
  arrange(
    Year,
    .by_group = TRUE
  ) %>%
  mutate(
    diff_km = Length_km - lag(Length_km),
    
    max_length = max(
      Length_km,
      na.rm = TRUE
    ),
    
    pct_max = diff_km / max_length,
    
    suspicious = if_else(
      !is.na(diff_km) &
        diff_km > RAIL_JUMP_KM &
        pct_max > RAIL_JUMP_PROP,
      TRUE,
      FALSE
    )
  ) %>%
  group_modify(
    ~ {
      df <- .x
      
      df %>%
        mutate(
          neg_nearby_10y = map_lgl(
            seq_len(n()),
            function(i) {
              
              yr_i <- df$Year[i]
              
              window <- df %>%
                filter(
                  Year >= yr_i - RAIL_JUMP_WINDOW,
                  Year <= yr_i + RAIL_JUMP_WINDOW,
                  Year != yr_i
                )
              
              cum_neg <- sum(
                window$diff_km[
                  window$diff_km < 0
                ],
                na.rm = TRUE
              )
              
              (cum_neg / df$max_length[i]) <
                -RAIL_JUMP_PROP
            }
          )
        )
    }
  ) %>%
  ungroup() %>%
  mutate(
    added_km = case_when(
      suspicious & neg_nearby_10y ~ 0,
      diff_km < 0 ~ 0,
      TRUE ~ diff_km
    )
  )



### Estimate ballast intensity from railway gauge ----------------------------

rail_with_gauge <- rail_diff %>%
  left_join(
    Railway_gauges,
    by = c("Country" = "country")
  ) %>%
  mutate(
    gauge_best_m = best / 1000,
    gauge_min_m = coalesce(min / 1000, gauge_best_m),
    gauge_max_m = coalesce(max / 1000, gauge_best_m),
    
    ballast_intensity_best = pmax(
      BALLAST_GAUGE_SLOPE * gauge_best_m +
        BALLAST_GAUGE_INTERCEPT,
      0
    ),
    
    ballast_intensity_min = pmax(
      BALLAST_GAUGE_SLOPE * gauge_min_m +
        BALLAST_GAUGE_INTERCEPT,
      0
    ),
    
    ballast_intensity_max = pmax(
      BALLAST_GAUGE_SLOPE * gauge_max_m +
        BALLAST_GAUGE_INTERCEPT,
      0
    ),
    
    ballast_new_best =
      added_km * ballast_intensity_best,
    
    ballast_new_min =
      added_km * ballast_intensity_min,
    
    ballast_new_max =
      added_km * ballast_intensity_max
  )


### Estimate ballast maintenance and renewal --------------------------------

rail_country <- rail_with_gauge %>%
  group_by(
    Country,
    Year
  ) %>%
  summarise(
    Length_km = first(Length_km),
    
    ballast_intensity_best = first(ballast_intensity_best),
    ballast_intensity_min = first(ballast_intensity_min),
    ballast_intensity_max = first(ballast_intensity_max),
    
    ballast_new_best = sum(
      ballast_new_best,
      na.rm = TRUE
    ),
    
    ballast_new_min = sum(
      ballast_new_min,
      na.rm = TRUE
    ),
    
    ballast_new_max = sum(
      ballast_new_max,
      na.rm = TRUE
    ),
    
    .groups = "drop"
  ) %>%
  mutate(
    renewed_km_min =
      Length_km * BALLAST_RENEWAL_MIN,
    
    renewed_km_best =
      Length_km * BALLAST_RENEWAL_BEST,
    
    renewed_km_max =
      Length_km * BALLAST_RENEWAL_MAX,
    
    ballast_renewal_min =
      renewed_km_min * ballast_intensity_min,
    
    ballast_renewal_best =
      renewed_km_best * ballast_intensity_best,
    
    ballast_renewal_max =
      renewed_km_max * ballast_intensity_max,
    
    ballast_total_min =
      ballast_new_min + ballast_renewal_min,
    
    ballast_total_best =
      ballast_new_best + ballast_renewal_best,
    
    ballast_total_max =
      ballast_new_max + ballast_renewal_max
  )


### Aggregate railway-ballast demand globally -------------------------------

rail_global <- rail_country %>%
  group_by(Year) %>%
  summarise(
    ballast_new_min = sum(
      ballast_new_min,
      na.rm = TRUE
    ),
    
    ballast_new_best = sum(
      ballast_new_best,
      na.rm = TRUE
    ),
    
    ballast_new_max = sum(
      ballast_new_max,
      na.rm = TRUE
    ),
    
    ballast_renewal_min = sum(
      ballast_renewal_min,
      na.rm = TRUE
    ),
    
    ballast_renewal_best = sum(
      ballast_renewal_best,
      na.rm = TRUE
    ),
    
    ballast_renewal_max = sum(
      ballast_renewal_max,
      na.rm = TRUE
    ),
    
    ballast_total_min = sum(
      ballast_total_min,
      na.rm = TRUE
    ),
    
    ballast_total_best = sum(
      ballast_total_best,
      na.rm = TRUE
    ),
    
    ballast_total_max = sum(
      ballast_total_max,
      na.rm = TRUE
    ),
    
    .groups = "drop"
  ) %>%
  mutate(
    # Convert tonnes yr-1 to Gt yr-1
    across(
      -Year,
      ~ .x / 1e9
    ),
    
    ballast_new_sd = sd_from_range(
      ballast_new_min,
      ballast_new_max,
      MC_COVERAGE_RAIL
    ),
    
    ballast_renewal_sd = sd_from_range(
      ballast_renewal_min,
      ballast_renewal_max,
      MC_COVERAGE_RAIL
    ),
    
    ballast_total_sd = sd_from_range(
      ballast_total_min,
      ballast_total_max,
      MC_COVERAGE_RAIL
    )
  )


### Propagate railway-ballast uncertainty -----------------------------------
SEED <- 27
set.seed(SEED)

rail_global_mc <- rail_global %>%
  rowwise() %>%
  mutate(
    ballast_new_draws = list(
      rnorm_trunc0(
        N_SIM_RAIL,
        ballast_new_best,
        ballast_new_sd
      )
    ),
    
    ballast_renewal_draws = list(
      rnorm_trunc0(
        N_SIM_RAIL,
        ballast_renewal_best,
        ballast_renewal_sd
      )
    ),
    
    ballast_total_draws = list(
      rnorm_trunc0(
        N_SIM_RAIL,
        ballast_total_best,
        ballast_total_sd
      )
    )
  ) %>%
  ungroup()
### Summarize railway-ballast reconstruction --------------------------------

rail_global_summary <- rail_global_mc %>%
  transmute(
    Year,
    
    ballast_new_mean =
      map_dbl(ballast_new_draws, mean),
    
    ballast_new_sd =
      map_dbl(ballast_new_draws, sd),
    
    ballast_renewal_mean =
      map_dbl(ballast_renewal_draws, mean),
    
    ballast_renewal_sd =
      map_dbl(ballast_renewal_draws, sd),
    
    aggregates_rail =
      map_dbl(ballast_total_draws, mean),
    
    aggregates_rail_sd =
      map_dbl(ballast_total_draws, sd),
    
    aggregates_rail_p05 =
      map_dbl(
        ballast_total_draws,
        ~ quantile(.x, 0.05)
      ),
    
    aggregates_rail_p50 =
      map_dbl(
        ballast_total_draws,
        ~ quantile(.x, 0.50)
      ),
    
    aggregates_rail_p95 =
      map_dbl(
        ballast_total_draws,
        ~ quantile(.x, 0.95)
      )
  )


# 04. Clay: cement production -----------------------------------------------

# Clay demand associated with cement production is estimated from annual
# cement production.
#
# Before the beginning of the USGS cement series, cement production is inferred
# from reconstructed concrete production using the assumed cement fraction of
# concrete (1/6 of total concrete mass).
#
# From 1927 onward, reported USGS cement-production statistics are used
# directly.
#
# Clay demand is then estimated assuming that clay represents 20% of cement
# mass.

cement <- USGS_cement %>%
  select(
    Year,
    Value
  ) %>%
  rename(
    cement_USGS = Value
  ) %>%
  right_join(
    data_concrete_asphalt,
    by = "Year"
  ) %>%
  mutate(
    cement_from_concrete =
      Concrete_total * CEMENT_FRACTION_CONCRETE,
    
    cement_total = case_when(
      Year < USGS_CEMENT_START_YEAR ~ cement_from_concrete,
      TRUE ~ cement_USGS
    )
  ) %>%
  arrange(Year) %>%
  select(
    Year,
    cement_total
  )

# Estimate clay demand associated with cement production.
clay_cement <- cement %>%
  mutate(
    clay_cement =
      cement_total * CLAY_FRACTION_CEMENT
  )



# 05. Limestone -------------------------------------------------------------

# Limestone demand is reconstructed from two main uses considered here:
#   1. limestone used in cement production;
#   2. limestone used in lime production.


## Limestone associated with cement production ------------------------------

# Limestone demand associated with cement production is assumed to equal
# total cement production on a 1:1 mass basis.

limestone_cement <- cement %>%
  mutate(
    limestone_cement =
      cement_total * LIMESTONE_TO_CEMENT_RATIO
  )


## Limestone associated with lime production --------------------------------

# Lime-production data are obtained from the harmonized mining dataset
# compiled for this study. USGS data for lime.
#
# Annual lime production is converted to a per-capita rate using global
# population. Outside the available temporal coverage, the per-capita rate
# observed in the first boundary year is propagated backward and that from the
# final boundary year is propagated forward.
#
# The reconstructed lime-production series is subsequently converted to
# limestone-equivalent mass using a factor of 1.8.

limestone_lime <- data_mining %>%
  filter(
    Element == "Ca" ) %>%
  transmute(
    Year,
    lime_production = as.numeric(Mining_Production)
  ) %>%
  right_join(
    population_OWD,
    by = "Year"
  ) %>%
  arrange(Year) %>%
  mutate(
    lime_production_per_capita =
      lime_production / Population
  )


# Extract the per-capita lime-production rates used to extend the series.

lime_pc_start <- limestone_lime %>%
  filter(
    Year == LIME_PC_START_YEAR
  ) %>%
  pull(
    lime_production_per_capita
  ) %>%
  first()

lime_pc_end <- limestone_lime %>%
  filter(
    Year == LIME_PC_END_YEAR
  ) %>%
  pull(
    lime_production_per_capita
  ) %>%
  first()


# Extend lime production outside the observed period and convert to
# limestone-equivalent mass.

limestone_lime <- limestone_lime %>%
  mutate(
    lime_production_per_capita = case_when(
      Year < LIME_PC_START_YEAR ~ lime_pc_start,
      Year > LIME_PC_END_YEAR ~ lime_pc_end,
      TRUE ~ lime_production_per_capita
    ),
    
    lime_production =
      lime_production_per_capita * Population,
    
    limestone_lime =
      lime_production * LIMESTONE_TO_LIME_RATIO
  )


# 06. Combine construction-material fluxes ----------------------------------

# Final annual construction-material mass fluxes are calculated separately
# for aggregates, clay, and limestone.
#
# Independent uncertainties are combined by quadrature where component-specific
# SD estimates are available.


## Aggregates ---------------------------------------------------------------

# Total virgin aggregate demand combines aggregates used in:
#   1. concrete;
#   2. asphalt;
#   3. road and building bases; and
#   4. railway ballast.

aggregates <- data_concrete_asphalt %>%
  select(
    Year,
    aggregates_concrete,
    aggregates_asphalt,
    aggregates_concrete_sd,
    aggregates_asphalt_sd
  ) %>%
  full_join(
    aggregates_bases %>%
      select(
        Year,
        aggregate_bases_virgin,
        aggregate_bases_virgin_sd
      ),
    by = "Year"
  ) %>%
  full_join(
    rail_global_summary %>%
      select(
        Year,
        aggregates_rail,
        aggregates_rail_sd
      ),
    by = "Year"
  ) %>%
  mutate(
    across(
      c(
        aggregates_concrete,
        aggregates_asphalt,
        aggregate_bases_virgin,
        aggregates_rail,
        aggregates_concrete_sd,
        aggregates_asphalt_sd,
        aggregate_bases_virgin_sd,
        aggregates_rail_sd
      ),
      ~ replace_na(.x, 0)
    ),
    
    aggregates_best =
      aggregates_concrete +
      aggregates_asphalt +
      aggregate_bases_virgin +
      aggregates_rail,
    
    aggregates_sd = sqrt(
      aggregates_concrete_sd^2 +
        aggregates_asphalt_sd^2 +
        aggregate_bases_virgin_sd^2 +
        aggregates_rail_sd^2
    )
  ) %>%
  arrange(Year) %>%
  select(
    Year,
    aggregates_best,
    aggregates_sd
  )


## Clay ---------------------------------------------------------------------

# Total clay demand combines clay associated with brick production and clay
# used in cement production.
#
# The annual CV inherited from the Plank et al. construction-material series is
# applied to the combined clay estimate.

clay <- data_brick %>%
  select(
    Year,
    clay_brick,
    CV
  ) %>%
  full_join(
    clay_cement %>%
      select(
        Year,
        clay_cement
      ),
    by = "Year"
  ) %>%
  mutate(
    clay_best = rowSums(
      across(
        c(
          clay_brick,
          clay_cement
        )
      ),
      na.rm = TRUE
    ),
    
    clay_sd =
      clay_best * CV
  ) %>%
  arrange(Year) %>%
  select(
    Year,
    clay_best,
    clay_sd
  )


## Limestone ----------------------------------------------------------------

# Total limestone demand combines limestone associated with cement production
# and limestone used as feedstock for lime production.
#
# The annual construction-material CV is applied to the combined limestone
# estimate.

limestone <- limestone_cement %>%
  select(
    Year,
    limestone_cement
  ) %>%
  full_join(
    limestone_lime %>%
      select(
        Year,
        limestone_lime
      ),
    by = "Year"
  ) %>%
  left_join(
    data_brick %>%
      select(
        Year,
        CV
      ),
    by = "Year"
  ) %>%
  mutate(
    limestone_cement = replace_na(
      limestone_cement,
      0
    ),
    
    limestone_lime = replace_na(
      limestone_lime,
      0
    ),
    
    limestone_best =
      limestone_cement +
      limestone_lime,
    
    limestone_sd =
      limestone_best * CV
  ) %>%
  arrange(Year) %>%
  select(
    Year,
    limestone_best,
    limestone_sd
  )


## Final construction-material dataset --------------------------------------

construction_mass <- aggregates %>%
  full_join(
    clay,
    by = "Year"
  ) %>%
  full_join(
    limestone,
    by = "Year"
  ) %>%
  arrange(Year)

write.csv(construction_mass, "data_construction.csv", row.names = F)


# 08. Validation checks -----------------------------------------------------
  
  # These checks compare reconstructed construction-material series against
  # independent estimates or overlapping source periods. 
  # They are are not required to generate the final construction dataset.

## Concrete reconstruction --------------------------------------------------

data_cement_validation <- data_cement_post2016 %>%
  left_join(
    data_aggregate_expanded,
    by = "Year"
  )

p_check_concrete <- ggplot(
  data_cement_validation,
  aes(x = Year, y = Concrete_total)
) +
  geom_line(linewidth = 1) +
  geom_line(
    aes(y = concrete_USGS),
    linewidth = 1
  ) +
  geom_ribbon(
    aes(
      ymin = Concrete_total - Concrete_total_sd,
      ymax = Concrete_total + Concrete_total_sd
    ),
    alpha = 0.3
  ) +
  labs(
    x = NULL,
    y = "Concrete production"
  ) +
  theme_bw()

## Railway consistency checks ----------------------------------------------
### Railway validation checks -----------------------------------------------

# These checks are diagnostic only. They are not used to generate the final
# railway-ballast reconstruction, but they help assess whether the estimated
# railway additions and ballast demand are plausible.


#### Cumulative additions vs maximum network length -------------------------

# Compare cumulative estimated railway additions with the maximum observed
# railway-network length for each country.
#
# Ratios moderately above 1 are expected because some railway lines may have
# been replaced, relocated, or reconstructed over time. Very high or very low
# ratios can indicate inconsistencies in the historical series.

rail_diff_check <- rail_diff %>%
  group_by(Country) %>%
  mutate(
    max_length = if_else(
      all(is.na(Length_km)),
      NA_real_,
      max(Length_km, na.rm = TRUE)
    ),
    
    ratio_added_max = if_else(
      is.finite(max_length) & max_length > 0,
      sum(added_km, na.rm = TRUE) / max_length,
      NA_real_
    )
  ) %>%
  ungroup()

# Country-level distribution of cumulative additions relative to maximum
# railway-network length.
rail_country_consistency <- rail_diff_check %>%
  group_by(Country) %>%
  summarise(
    total_added_km = sum(
      added_km,
      na.rm = TRUE
    ),
    
    max_length_km = first(
      max_length
    ),
    
    ratio_added_max = first(
      ratio_added_max
    ),
    
    .groups = "drop"
  ) %>%
  filter(
    is.finite(max_length_km),
    max_length_km > 0
  ) %>%
  arrange(
    desc(ratio_added_max)
  )

# Global consistency check.
rail_global_consistency <- rail_country_consistency %>%
  summarise(
    total_added_km = sum(
      total_added_km,
      na.rm = TRUE
    ),
    
    total_max_length_km = sum(
      max_length_km,
      na.rm = TRUE
    ),
    
    ratio_added_max =
      total_added_km / total_max_length_km
  )



#### Alternative railway-ballast estimate -----------------------------------

### Estimate ballast intensity from railway gauge ----------------------------
rail_with_gauge <- rail_diff %>%
  left_join(
    Railway_gauges,
    by = c("Country" = "country")
  ) %>%
  mutate(
    gauge_best_m = best / 1000,
    gauge_min_m = coalesce(min / 1000, gauge_best_m),
    gauge_max_m = coalesce(max / 1000, gauge_best_m),
    
    ballast_intensity_best = pmax(
      BALLAST_GAUGE_SLOPE * gauge_best_m +
        BALLAST_GAUGE_INTERCEPT,
      0
    ),
    
    ballast_intensity_min = pmax(
      BALLAST_GAUGE_SLOPE * gauge_min_m +
        BALLAST_GAUGE_INTERCEPT,
      0
    ),
    
    ballast_intensity_max = pmax(
      BALLAST_GAUGE_SLOPE * gauge_max_m +
        BALLAST_GAUGE_INTERCEPT,
      0
    ),
    
    ballast_new_best =
      added_km * ballast_intensity_best,
    
    ballast_new_min =
      added_km * ballast_intensity_min,
    
    ballast_new_max =
      added_km * ballast_intensity_max
  )

# As an independent plausibility check, ballast demand for newly constructed
# railway is also estimated using the geometric approach described by
# Zhuang et al. (2025).
#
# This validation assumes a ballast depth of 0.37 m and bulk density of
# 1540 kg m-3. Railway gauge is used as a proxy for ballast width.
#
# These estimates are used only for comparison with the Miatto et al. (2017)
# reconstruction and are not included in the final construction-material
# dataset.

ZHUANG_BALLAST_DEPTH_M <- 0.37
ZHUANG_BALLAST_DENSITY_KG_M3 <- 1540


rail_validation <- rail_with_gauge %>%
  mutate(
    zhuang_volume_best_m3 = if_else(
      !is.na(added_km) &
        !is.na(gauge_best_m),
      
      added_km *
        1000 *
        gauge_best_m *
        ZHUANG_BALLAST_DEPTH_M,
      
      NA_real_
    ),
    
    zhuang_ballast_best_t =
      zhuang_volume_best_m3 *
      ZHUANG_BALLAST_DENSITY_KG_M3 /
      1000
  )


rail_method_comparison <- rail_validation %>%
  group_by(Year) %>%
  summarise(
    miatto_best = sum(
      ballast_new_best,
      na.rm = TRUE
    ),
    
    zhuang_best = sum(
      zhuang_ballast_best_t,
      na.rm = TRUE
    ),
    
    .groups = "drop"
  ) %>%
  mutate(
    # Convert tonnes to Mt for plotting
    miatto_best = miatto_best / 1e6,
    zhuang_best = zhuang_best / 1e6
  )

p_rail_method_validation <- rail_method_comparison %>%
  pivot_longer(
    cols = c(
      miatto_best,
      zhuang_best
    ),
    names_to = "Method",
    values_to = "Ballast_Mt"
  ) %>%
  ggplot(
    aes(
      x = Year,
      y = Ballast_Mt,
      colour = Method
    )
  ) +
  geom_line(
    linewidth = 1
  ) +
  labs(
    x = NULL,
    y = "Railway ballast demand (Mt yr-1)",
    colour = "Method"
  ) +
  theme_bw()
